version: '3.8'

networks:
  kube_net:
    driver: bridge

volumes:
  postgres_vol:

services:

  kubenews:
    container_name: kubenews
    image: isaacgiordani/kube-news:v1
    restart: always
    ports:
      - 8080:8080
    networks:
      - kube_net
    depends_on:
      - postgres
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}

  postgres:
    container_name: postgres
    image: postgres:14.5
    restart: always
    ports:
      - 5432:5432
    networks:
      - kube_net
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata