version: '3.8'

networks:
  wordpress_net:
    driver: bridge

volumes:
  db:
  wordpress:

services:

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    networks:
      - wordpress_net
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
      container_name: wordpress
      image: wordpress
      restart: always
      ports:
        - 8080:80
      networks:
        - wordpress_net
      depends_on:
        - db
      volumes:
        - wordpress:/var/www/html
      environment:
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}