version: '3.8'

networks:
  rotten_net:
    driver: bridge

volumes:
  mongo_data:

services:

  rotten:
    container_name: rotten
    image: isaacgiordani/rotten-potatoes:v1
    restart: always
    ports:
      - 5000:5000
    networks:
      - rotten_net
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  mongodb:
    container_name: mongodb
    image: mongo:5.0.0
    restart: always
    networks:
      - rotten_net
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}