version: '3.8'

networks:
  mongo_net:
    driver: bridge

volumes:
  mongo_vol:

services:

  mongo:
    container_name: mongo
    image: mongo:6.0.1-focal
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo_net
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${username}
      MONGO_INITDB_ROOT_PASSWORD: ${password}

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - mongo_net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${username}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${password}
      ME_CONFIG_MONGODB_URL: mongodb://${username}:${password}@mongo:27017/
